# Generated by Django 4.2.5 on 2023-09-15 11:48

import booking_brain.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Middle_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(max_length=50)),
                ('Departure_place', models.CharField(max_length=50)),
                ('Destination', models.CharField(max_length=50)),
                ('Departure_date', models.DateField()),
                ('Return_date', models.DateField()),
                ('Amount', models.IntegerField()),
                ('ReadyForBooking', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Payment_method', models.CharField(max_length=50)),
                ('Payment_status', models.CharField(max_length=20)),
                ('Payment_ref', models.CharField(max_length=50)),
                ('Payment_date', models.DateField()),
                ('Amount', models.IntegerField()),
                ('Amount_EA', models.IntegerField()),
                ('Amount_M_com', models.IntegerField()),
                ('Amount_Z_com', models.IntegerField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_brain.passenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Passport_country', models.CharField(max_length=50)),
                ('Passport_no', models.CharField(max_length=50)),
                ('Passport_expiry', models.DateField()),
                ('Date_birth', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Booking_no', models.CharField(default=booking_brain.models.generate_unique_code, max_length=5, unique=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_brain.passenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
