# Generated by Django 4.2.5 on 2023-09-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_brain', '0002_remove_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_status',
            field=models.BooleanField(default=True),
        ),
    ]
