# Generated by Django 4.2.5 on 2023-09-21 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_brain', '0003_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Ticket_no',
            field=models.CharField(default=datetime.datetime(2023, 9, 21, 20, 11, 46, 173807, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
