# Generated by Django 4.2.5 on 2023-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_brain', '0006_alter_payment_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='Return_date',
            field=models.DateField(null=True),
        ),
    ]
